# Defining ApiVersion
apiVersion: v1
kind: Pod
metadata:
  name: demoPod
  type: demo
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8080
      restartPolicy: OnFailure
